name: rctool
description: "RcTool"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.9
  get: ^4.6.1
  cupertino_icons: ^1.0.8
  audioplayers: ^6.1.0
  flutter_cache_manager: ^3.3.0
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.0.1
  sqflite: ^2.4.1
  path: ^1.9.0
  headset_connection_event: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: RcIcon
      fonts:
        - asset: fonts/iconfont.ttf
  assets:
    - image/RcTool.png
